# Generated by Django 3.1.3 on 2020-11-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
    ]
