# Generated by Django 3.1.3 on 2020-11-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_auto_20201123_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='questionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('chapter', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('unit', models.IntegerField()),
                ('sem', models.IntegerField()),
                ('year', models.IntegerField()),
                ('subname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'questionBank',
            },
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
